services:
  textbee-web:
    image: textbee-web
    container_name: textbee-web
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: 
      - path: ./web/.env
        required: true
    command: pnpm start
  textbee-api:
    image: textbee-api
    container_name: textbee-api
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    env_file: 
      - path: ./api/.env
        required: true
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
